### ISSUE TITLE
URL Error

### ISSUE THREAD

**Issue by dorajam** [ChainsawPolice/soundcloud-page-downloader#9]
It seems like none of the users are recognized hmm... Any ideas on what might be wrong? I'm getting the following error message in urllib2.py:

urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by nsipplswezey** [comment]
Same 
```
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

**Comment by Deleetdk** [comment]
Not maintained I think, but just in case:

```
(env) user@computer:~/apps/soundcloud-page-downloader$ python soundcloud-downloader.py -u moon_music
SoundCloud Page Downloader
By J. Merriman -

Track 1/29
Traceback (most recent call last):
  File "soundcloud-downloader.py", line 127, in <module>
    main(parsed_args)
  File "soundcloud-downloader.py", line 109, in main
    track['user']['permalink'], track_title, track_genre)
  File "soundcloud-downloader.py", line 47, in download_file
    u = urllib2.urlopen(download_url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```

This is using python 2.7, install fails with python 3:

```
(env) user@computer:~/apps/soundcloud-page-downloader$ pip install -r requirements.txt
Collecting mutagen==1.23 (from -r requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/9e/33/c4831d3266edc5deb7eacffb37dd31a63bfa9f26a055d1964377e701d909/mutagen-1.23.tar.gz (835kB)
    100% |████████████████████████████████| 839kB 2.4MB/s 
Collecting requests==2.3.0 (from -r requirements.txt (line 2))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/f7/51/7aa1e337862118bee783c0249debd64cb07b8fbdfef154b1e185754b02d5/requests-2.3.0-py2.py3-none-any.whl (452kB)
    100% |████████████████████████████████| 460kB 2.4MB/s 
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xqek3_zq/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-xqek3_zq/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xqek3_zq/wsgiref/
```
